##
## Blender Render (v5.1) - English interface for VMD
##

# This companion script keeps the English interface synchronized with the
# maintained Render2K implementation without duplicating its rendering logic.
if {[namespace exists ::Render2KEnglish]} {
    namespace delete ::Render2KEnglish
}

namespace eval ::Render2KEnglish {
    variable translations [list \
        "Render2K Blender (v5.1) - Renderizador Blender para VMD" "Render2K Blender (v5.1) - Blender renderer for VMD" \
        "Perfiles Principled BSDF configurables desde VMD." "Principled BSDF profiles configurable from VMD." \
        "Blender Render v5.1 cargado" "Blender Render v5.1 loaded" \
        "Acceso: Extensions -> Rendering -> Blender Render" "Access: Extensions -> Rendering -> Blender Render" \
        "Listo para renderizar una pelicula." "Ready to render a movie." \
        "Sin trabajo activo" "No active job" \
        "conversion fallo:" "conversion failed:" \
        "no detectada" "not detected" \
        "no disponible" "unavailable" \
        "OBJ reescrito:" "OBJ rewritten:" \
        "representaciones mapeadas" "mapped representations" \
        "perfiles por representacion:" "profiles by representation:" \
        "ADVERTENCIA:" "WARNING:" \
        "perfiles VMD sin mapa Blender:" "VMD profiles without a Blender mapping:" \
        "; se usa Default" "; Default is used" \
        "Perfil Blender no valido." "Invalid Blender profile." \
        "Alpha y Transmision son modos excluyentes. Usa Alpha para transparencia clara, o Alpha=1 con Transmision para vidrio fisico." "Alpha and Transmission are mutually exclusive modes. Use Alpha for clear transparency, or Alpha=1 with Transmission for physical glass." \
        " guardado para el proximo render Blender." " saved for the next Blender render." \
        " cargado." " loaded." \
        "Perfil '" "Profile '" \
        " debe ser un numero entre " " must be a number between " \
        " debe estar entre " " must be between " \
        "Rugosidad" "Roughness" \
        "Nivel especular" "Specular level" \
        "Transmision" "Transmission" \
        "No se pudo importar OBJ %s: %s" "Could not import OBJ %s: %s" \
        "OBJ sin geometria" "OBJ has no geometry" \
        "R2K: Aplicando perfiles Principled BSDF de Blender..." "R2K: Applying Blender Principled BSDF profiles..." \
        "Perfil Blender no definido para %s: %s" "Blender profile is not defined for %s: %s" \
        "Alpha y Transmission no se pueden combinar: %s" "Alpha and Transmission cannot be combined: %s" \
        "Materiales OBJ sin perfil Blender:" "OBJ materials without a Blender profile:" \
        "No se pudo crear el World node tree" "Could not create the World node tree" \
        "Motor solicitado invalido: %r" "Invalid requested engine: %r" \
        "Motor %s no disponible" "Engine %s is unavailable" \
        "Cycles no esta disponible" "Cycles is unavailable" \
        "No se pudieron configurar samples de Cycles" "Could not configure Cycles samples" \
        "No hay ajustes Eevee disponibles" "No Eevee settings are available" \
        "No se pudieron configurar samples de Eevee" "Could not configure Eevee samples" \
        "El fondo plano requiere el transform Standard" "The flat background requires the Standard transform" \
        "Auto-generado por Render2K Blender: worker de pelicula" "Generated by Render2K Blender: movie worker" \
        "Auto-generado por Render2K Blender" "Generated by Render2K Blender" \
        "Perfiles Principled BSDF configurados en la interfaz de Render2K." "Principled BSDF profiles configured in the Render2K interface." \
        "Asociacion exacta de cada material MTL generado con su perfil Blender." "Exact association of each generated MTL material with its Blender profile." \
        "No se infiere desde el nombre para evitar que un fallo termine en Default." "It is not inferred from the name so a failure cannot fall back to Default." \
        "El importador OBJ de Blender no siempre transfiere Kd al Principled." "Blender's OBJ importer does not always transfer Kd to Principled." \
        "Se serializa el RGB que VMD exporto para preservar cada Color Scale." "The RGB exported by VMD is serialized to preserve every Color Scale." \
        "PERFILES BLENDER -> PRINCIPLED BSDF (asignados por representacion)" "BLENDER PROFILES -> PRINCIPLED BSDF (assigned by representation)" \
        "Nombres generados por Render2K:" "Names generated by Render2K:" \
        "No dependemos del Kd que Blender importe: conserva Color Scale." "Do not rely on Blender-imported Kd: preserve Color Scale." \
        "CAMARA ORTOGRAFICA" "ORTHOGRAPHIC CAMERA" \
        "Iluminacion" "Lighting" \
        "Fondo visible e iluminacion del mundo" "Visible background and world lighting" \
        "La camara ve el color, pero iluminacion y reflejos reciben negro." "The camera sees the color, while lighting and reflections receive black." \
        "Motor Blender y sus opciones especificas" "Blender engine and its specific options" \
        "Blender no esta disponible." "Blender is unavailable." \
        "no se pudo iniciar Blender:" "could not start Blender:" \
        "blender termino con:" "Blender exited with:" \
        "exportando escena Wavefront OBJ (puede tardar en escenas grandes)..." "exporting Wavefront OBJ scene (large scenes may take a while)..." \
        "VMD no genero el archivo" "VMD did not generate the file" \
        "Colores Wavefront:" "Wavefront colors:" \
        "RGB conservados desde MTL" "RGB values preserved from MTL" \
        "MTL sin colores Kd; se usara colorinfo como respaldo" "MTL has no Kd colors; colorinfo will be used as a fallback" \
        "Materiales Blender:" "Blender materials:" \
        "materiales generados desde perfiles Principled BSDF" "materials generated from Principled BSDF profiles" \
        "OBJ+MTL+script listos (modo 'solo exportar'):" "OBJ+MTL+script ready (export-only mode):" \
        "Escena exportada" "Scene exported" \
        "Archivos generados:" "Generated files:" \
        "Para renderizar:" "To render:" \
        "lanzando Blender headless" "launching headless Blender" \
        "Error exportando OBJ" "OBJ export error" \
        "Error de Blender" "Blender error" \
        "Blender no genero la imagen.\nRevisa la consola de VMD." "Blender did not generate the image.\nCheck the VMD console." \
        "Motor no soportado" "Unsupported engine" \
        "Blender Render solo renderiza con Blender." "Blender Render renders only with Blender." \
        "No se encontro el ejecutable Blender en PATH." "The Blender executable was not found in PATH." \
        "Resolucion invalida" "Invalid resolution" \
        "El ancho de resoluci\u00f3n debe ser un entero positivo." "The resolution width must be a positive integer." \
        "El alto de resoluci\u00f3n debe ser un entero positivo." "The resolution height must be a positive integer." \
        "El ancho de resoluci\u00f3n debe estar entre 1 y 32768 px." "The resolution width must be between 1 and 32768 px." \
        "El alto de resoluci\u00f3n debe estar entre 1 y 32768 px." "The resolution height must be between 1 and 32768 px." \
        "RENDER Blender destino=" "Blender RENDER target=" \
        " archivo=" " file=" \
        "RENDERIZADO COMPLETADO en" "RENDER COMPLETED in" \
        "Archivo:" "File:" \
        "RENDER fallido o cancelado" "RENDER failed or cancelled" \
        "La molecula debe ser 'top' o un identificador numerico de VMD." "The molecule must be 'top' or a numeric VMD identifier." \
        "La molecula VMD '" "VMD molecule '" \
        "' no esta disponible." "' is unavailable." \
        "CRC cancelado" "CRC cancelled" \
        "No se pudo verificar la fuente de volumen" "Could not verify volume source" \
        "No se pudieron leer los \u00e1tomos de la mol\u00e9cula" "Could not read atoms from molecule" \
        "La pelicula fue cancelada." "The movie was cancelled." \
        "Falta el asset" "Missing asset" \
        "para el frame VMD" "for VMD frame" \
        "No se pudo verificar el asset Blender" "Could not verify Blender asset" \
        "No hay registro de assets para el frame VMD" "No asset record exists for VMD frame" \
        "No se pudo verificar el PNG del frame VMD" "Could not verify PNG for VMD frame" \
        "No se pudo calcular la integridad del PNG" "Could not calculate PNG integrity" \
        "El lote ya esta bloqueado por otro proceso o quedo un bloqueo pendiente:" "The batch is already locked by another process or has a stale lock:" \
        "El directorio de assets existe pero no pertenece a este lote:" "The asset directory exists but does not belong to this batch:" \
        "El manifiesto de pelicula no es valido:" "The movie manifest is invalid:" \
        "Los assets existentes pertenecen a otra pelicula; elige otro archivo de salida." "Existing assets belong to another movie; choose another output file." \
        "Pel\u00edcula cancelada. Los assets se conservaron para reanudar." "Movie cancelled. Assets were retained so it can be resumed." \
        "Cancelada" "Cancelled" \
        "PEL\u00cdCULA cancelada; los frames y escenas parciales se conservaron." "MOVIE cancelled; partial frames and scenes were retained." \
        "Fallida" "Failed" \
        "PEL\u00cdCULA fallida:" "MOVIE failed:" \
        "Error de pelicula Blender" "Blender movie error" \
        "Los assets se conservaron para diagnostico o reanudacion." "Assets were retained for diagnosis or resuming." \
        "Blender renderiza frame VMD" "Blender is rendering VMD frame" \
        "Blender renderiza" "Blender is rendering" \
        "en un unico lote." "in a single batch." \
        "iniciando un unico proceso Blender para" "starting a single Blender process for" \
        "Faltan PNG en la secuencia; no se codificara un MP4 incompleto." "PNG files are missing from the sequence; an incomplete MP4 will not be encoded." \
        "FFmpeg codifica el MP4 H.264..." "FFmpeg is encoding the H.264 MP4..." \
        "Codificando MP4" "Encoding MP4" \
        "PEL\u00cdCULA: codificando MP4 con FFmpeg a" "MOVIE: encoding MP4 with FFmpeg to" \
        "FFmpeg termino sin generar el MP4 temporal." "FFmpeg exited without generating the temporary MP4." \
        "La ruta MP4 final es un directorio y no se puede publicar la pel\u00edcula." "The final MP4 path is a directory and the movie cannot be published." \
        "El MP4 final apareci\u00f3 durante el render y no se sobrescribir\u00e1 sin autorizaci\u00f3n." "The final MP4 appeared during rendering and will not be overwritten without authorization." \
        "No se pudo publicar el MP4 final sin sobrescribir:" "Could not publish the final MP4 without overwriting:" \
        "No se pudo publicar el MP4 final:" "Could not publish the final MP4:" \
        "La ruta MP4 se convirti\u00f3 en un directorio durante la publicaci\u00f3n." "The MP4 path became a directory during publication." \
        "No se pudo verificar el MP4 publicado." "Could not verify the published MP4." \
        "Completada" "Completed" \
        "Pel\u00edcula completada:" "Movie completed:" \
        " (assets limpiados)" " (assets cleaned up)" \
        "PEL\u00cdCULA COMPLETADA:" "MOVIE COMPLETED:" \
        "Forzando cancelacion de pelicula..." "Forcing movie cancellation..." \
        "Cancelando pelicula..." "Cancelling movie..." \
        "No se pudo iniciar" "Could not start" \
        "termino con error:" "exited with an error:" \
        "Blender no confirmo todos los frames del lote." "Blender did not confirm every frame in the batch." \
        "Blender termino sin producir todos los PNG de la secuencia." "Blender exited without producing every PNG in the sequence." \
        "No se pudo registrar la integridad de los PNG:" "Could not record PNG integrity:" \
        "Los assets de un frame pendiente no coinciden con el manifiesto." "Assets for a pending frame do not match the manifest." \
        "No se pudo generar el worker Blender:" "Could not generate the Blender worker:" \
        "Frame VMD" "VMD frame" \
        "ya esta renderizado" "is already rendered" \
        "PEL\u00cdCULA: se reutiliza PNG del frame VMD" "MOVIE: reusing PNG for VMD frame" \
        "Se reanuda escena VMD" "Resuming VMD scene" \
        "PEL\u00cdCULA: se reutilizan assets del frame VMD" "MOVIE: reusing assets for VMD frame" \
        "Exportando frame VMD" "Exporting VMD frame" \
        "No se pudo activar el frame VMD" "Could not activate VMD frame" \
        "No se pudo verificar la escena VMD del frame" "Could not verify the VMD scene for frame" \
        "La escena VMD cambi\u00f3 durante el lote; no se mezclar\u00e1n frames con estados distintos." "The VMD scene changed during the batch; frames with different states will not be mixed." \
        "No se pudo verificar el estado del frame VMD" "Could not verify the state of VMD frame" \
        "No se pudo exportar el frame VMD" "Could not export VMD frame" \
        "No se pudo registrar el frame VMD" "Could not record VMD frame" \
        "Todos los PNG ya existen; se codificara el MP4." "All PNG files already exist; the MP4 will be encoded." \
        "PNG reutilizados" "PNG files reused" \
        "Exportacion VMD completada; preparando Blender." "VMD export completed; preparing Blender." \
        "VMD completado" "VMD completed" \
        "Pel\u00edcula en curso" "Movie in progress" \
        "Ya hay una pel\u00edcula Blender en proceso." "A Blender movie is already in progress." \
        "FFmpeg no disponible" "FFmpeg unavailable" \
        "Se necesita ffmpeg para codificar la secuencia PNG a MP4." "ffmpeg is required to encode the PNG sequence as MP4." \
        "Rango de frames invalido" "Invalid frame range" \
        "Inicio, final y salto deben ser enteros; el salto debe ser mayor que cero." "Start, end, and stride must be integers; stride must be greater than zero." \
        "FPS invalido" "Invalid FPS" \
        "Configura entre 1 y 240 FPS." "Set a value between 1 and 240 FPS." \
        "CRF invalido" "Invalid CRF" \
        "CRF debe estar entre 0 y 51; 18 es alta calidad." "CRF must be between 0 and 51; 18 is high quality." \
        "Molecula invalida" "Invalid molecule" \
        "La molecula" "Molecule" \
        "contiene frames entre" "contains frames from" \
        "Sin frames" "No frames" \
        "El rango seleccionado no produce frames para renderizar." "The selected range does not produce frames to render." \
        "Archivo de pelicula invalido" "Invalid movie file" \
        "Archivo MP4 invalido" "Invalid MP4 file" \
        "La ruta de salida es un directorio:" "The output path is a directory:" \
        "Escena VMD invalida" "Invalid VMD scene" \
        "No se pudo preparar la pelicula" "Could not prepare the movie" \
        "No se pudo crear" "Could not create" \
        "Lote de pelicula ocupado" "Movie batch is busy" \
        "MP4 existente" "Existing MP4" \
        "Ya existe" "Already exists" \
        ". Activa 'Sobrescribir MP4 existente' o elige otro archivo." ". Enable 'Overwrite existing MP4' or choose another file." \
        "Assets de pelicula invalidos" "Invalid movie assets" \
        "Preparando" "Preparing" \
        "para Blender; ajustes congelados para este lote." "for Blender; settings are frozen for this batch." \
        "PEL\u00cdCULA Blender frames=" "Blender MOVIE frames=" \
        "salto=" "stride=" \
        "destino=" "target=" \
        "c\u00e1mara" "camera" \
        "bloqueada" "locked" \
        "por frame" "per frame" \
        "Personalizada:" "Custom:" \
        "Seleccionada:" "Selected:"]
}

proc ::Render2KEnglish::translate {text} {
    variable translations
    return [string map $translations $text]
}

# Translate load-time status output without changing the global puts command
# after the companion script has finished loading.
proc ::Render2KEnglish::source_puts {args} {
    set text_index [expr {[llength $args] - 1}]
    if {$text_index >= 0} {
        set args [lreplace $args $text_index $text_index \
            [translate [lindex $args $text_index]]]
    }
    ::Render2KEnglish::original_puts {*}$args
}

set render2k_english_dir [file dirname [file normalize [info script]]]
set render2k_english_source [file join $render2k_english_dir render2K.tcl]
if {![file exists $render2k_english_source]} {
    error "Render2K source script not found: $render2k_english_source"
}

rename ::puts ::Render2KEnglish::original_puts
proc ::puts {args} {
    ::Render2KEnglish::source_puts {*}$args
}
set render2k_english_rc [catch {source $render2k_english_source} \
    render2k_english_error render2k_english_options]
rename ::puts {}
rename ::Render2KEnglish::original_puts ::puts
if {$render2k_english_rc} {
    return -options $render2k_english_options $render2k_english_error
}
unset render2k_english_dir render2k_english_source render2k_english_rc
unset render2k_english_error render2k_english_options

proc ::Render2K::log {message} {
    puts "blender-render: [::Render2KEnglish::translate $message]"
}

proc ::Render2K::msg {icon title text} {
    set title [::Render2KEnglish::translate $title]
    set text [::Render2KEnglish::translate $text]
    log "$title -- $text"
    catch { tk_messageBox -type ok -icon $icon -message $text -title $title }
}

proc ::Render2KEnglish::translate_variable {name1 name2 operation} {
    upvar #0 $name1 value
    if {[info exists value]} {
        set value [translate $value]
    }
}

foreach variable {
    ::Render2K::movie_status
    ::Render2K::movie_progress_text
    ::Render2K::blender_mat_status
    ::Render2K::resolution_info
} {
    set $variable [::Render2KEnglish::translate [set $variable]]
    trace add variable $variable write ::Render2KEnglish::translate_variable
}
unset variable

# Blender executes the generated Python outside Tcl, so translate its comments,
# diagnostics, and progress output after the original generator writes it.
proc ::Render2KEnglish::translate_generated_file {path} {
    set input [open $path r]
    set contents [read $input]
    close $input
    set temporary "${path}.[clock clicks].tmp"
    set output [open $temporary w]
    puts -nonewline $output [translate $contents]
    close $output
    file rename -force $temporary $path
}

rename ::Render2K::gen_blender_py ::Render2K::gen_blender_py_original
proc ::Render2K::gen_blender_py {pyscript args} {
    set result [gen_blender_py_original $pyscript {*}$args]
    ::Render2KEnglish::translate_generated_file $pyscript
    return $result
}

proc ::Render2K::update_resolution_fields {} {
    variable w
    variable resolution_preset
    variable custom_width
    variable custom_height
    variable resolutions
    variable resolution_info
    if {![winfo exists $w]} { return }
    set r $w.main.r
    if {$resolution_preset eq "Custom"} {
        $r.res.custom.width configure -state normal
        $r.res.custom.height configure -state normal
        set resolution_info "Custom: ${custom_width} x ${custom_height} px"
    } else {
        $r.res.custom.width configure -state disabled
        $r.res.custom.height configure -state disabled
        set res $resolutions($resolution_preset)
        set resolution_info "Selected: [lindex $res 0] x [lindex $res 1] px"
    }
}

proc ::Render2K::render2k_window {} {
    variable w
    variable resolution_preset
    variable bg_color
    variable engine

    detect_all
    set engine "blender"

    if {$w ne "" && ![catch {winfo exists $w} exists] && $exists} {
        catch { wm deiconify $w }
        catch { raise $w }
        catch { focus -force $w }
        return $w
    }
    set w ""
    if {[winfo exists .render2k]} { catch { destroy .render2k } }
    set w [toplevel .render2k]
    wm title $w "Blender Render (VMD) - v5.1"
    wm resizable $w 0 0
    wm protocol $w WM_DELETE_WINDOW ::Render2K::close_window

    label $w.title -text "Blender Render" -font {-weight bold -size 11}
    pack $w.title -pady 4

    label $w.status -justify left -font {-size 8} -anchor w -padx 8
    pack $w.status -fill x -pady 2
    set txt "Blender: [expr {$::Render2K::have_blender ne 0 ? "OK" : "unavailable"}]"
    append txt "  |  GPU: [expr {$::Render2K::gpu_name ne "" ? $::Render2K::gpu_name : "not detected"}]"
    append txt "  |  FFmpeg: [expr {$::Render2K::have_ffmpeg ne 0 && $::Render2K::have_ffmpeg ne "" ? "OK" : "unavailable"}]"
    $w.status configure -text $txt \
        -fg [expr {$::Render2K::have_blender ne 0 ? "#006600" : "#aa0000"}]

    frame $w.bar
    pack $w.bar -fill x -padx 6
    button $w.bar.b1 -text "Render" -width 18 -relief sunken -bg "#90caf9" \
        -command [list ::Render2K::show_tab r]
    button $w.bar.b2 -text "Blender Materials" -width 20 -relief raised -bg "#e0e0e0" \
        -command [list ::Render2K::show_tab m]
    button $w.bar.b3 -text "Blender Movie" -width 18 -relief raised -bg "#e0e0e0" \
        -command [list ::Render2K::show_tab v]
    pack $w.bar.b1 $w.bar.b2 $w.bar.b3 -side left -padx 2 -pady 2 -expand 1 -fill x

    frame $w.main
    pack $w.main -fill both -expand 1 -padx 6 -pady 2
    frame $w.main.r
    frame $w.main.m
    frame $w.main.v

    set r $w.main.r
    labelframe $r.eng -text "Blender Engine" -font {-weight bold -size 9} -padx 6 -pady 4
    pack $r.eng -side top -fill x -pady 2
    frame $r.eng.row
    pack $r.eng.row -side top -fill x
    label $r.eng.row.l -text "Renderer:" -font {-size 9} -width 13 -anchor w
    radiobutton $r.eng.row.cycles -text "Cycles" -font {-size 9} \
        -variable ::Render2K::blender_render_engine -value CYCLES
    radiobutton $r.eng.row.eevee -text "Eevee" -font {-size 9} \
        -variable ::Render2K::blender_render_engine -value EEVEE
    pack $r.eng.row.l -side left -padx 4
    pack $r.eng.row.cycles $r.eng.row.eevee -side left -padx 6
    label $r.eng.info -text "Cycles uses the GPU when available; Eevee prioritizes speed." \
        -font {-size 8} -anchor w -fg "#555555"
    pack $r.eng.info -side top -anchor w -padx 4 -pady 1

    labelframe $r.bl -text "Blender Options" -font {-weight bold -size 9} -padx 6 -pady 4
    pack $r.bl -side top -fill x -pady 2
    frame $r.bl.s1; pack $r.bl.s1 -side top -fill x
    label $r.bl.s1.l -text "Samples:" -font {-size 9} -width 12 -anchor w
    spinbox $r.bl.s1.s -from 16 -to 2048 -increment 16 -width 7 \
        -textvariable ::Render2K::blender_samples -font {-size 9}
    checkbutton $r.bl.s1.d -text "Denoise (Cycles)" -font {-size 9} \
        -variable ::Render2K::blender_denoise
    pack $r.bl.s1.l -side left -padx 4
    pack $r.bl.s1.s -side left -padx 2
    pack $r.bl.s1.d -side left -padx 12
    frame $r.bl.s2; pack $r.bl.s2 -side top -fill x
    checkbutton $r.bl.s2.a -text "Render automatically in Blender" \
        -font {-size 9} -variable ::Render2K::blender_autorun
    checkbutton $r.bl.s2.o -text "Match VMD orientation" -font {-size 9} \
        -variable ::Render2K::blender_rotate
    pack $r.bl.s2.a -side left -padx 4
    pack $r.bl.s2.o -side left -padx 12

    frame $r.bl.s3; pack $r.bl.s3 -side top -fill x -pady 2 -anchor w
    label $r.bl.s3.l -text "Blender background:" -font {-size 9} -width 14 -anchor w
    tk_optionMenu $r.bl.s3.m ::Render2K::bg_color black white "8" current
    pack $r.bl.s3.l -side left -padx 4
    pack $r.bl.s3.m -side left -padx 4

    frame $r.bl.s4; pack $r.bl.s4 -side top -fill x -pady 2 -anchor w
    label $r.bl.s4.l -text "Background mode:" -font {-size 9} -width 14 -anchor w
    radiobutton $r.bl.s4.flat -text "Flat, unlit" -font {-size 9} \
        -variable ::Render2K::blender_background_mode -value flat \
        -command ::Render2K::update_background_controls
    radiobutton $r.bl.s4.world -text "World lighting" -font {-size 9} \
        -variable ::Render2K::blender_background_mode -value world \
        -command ::Render2K::update_background_controls
    pack $r.bl.s4.l -side left -padx 4
    pack $r.bl.s4.flat $r.bl.s4.world -side left -padx 4

    frame $r.bl.s5; pack $r.bl.s5 -side top -fill x -pady 2 -anchor w
    label $r.bl.s5.l -text "World strength:" -font {-size 9} -width 14 -anchor w
    scale $r.bl.s5.s -from 0.0 -to 3.0 -resolution 0.05 -orient horizontal -font {-size 9} \
        -variable ::Render2K::blender_bg_strength -length 190 -showvalue 1
    label $r.bl.s5.note -text "Flat mode uses the exact color without affecting light or reflections." \
        -font {-size 8} -anchor w -fg "#555555"
    pack $r.bl.s5.l -side left -padx 4
    pack $r.bl.s5.s -side left -padx 4
    pack $r.bl.s5.note -side left -padx 4

    labelframe $r.res -text "Resolution" -font {-weight bold -size 9} -padx 6 -pady 4
    pack $r.res -side top -fill x -pady 2
    frame $r.res.presets
    pack $r.res.presets -side top -fill x -pady 1
    set row 0; set col 0
    foreach preset {HD\ \(1280x720\) Full\ HD\ \(1920x1080\) 2K\ \(2560x1440\) \
                    4K\ \(3840x2160\) 5K\ \(5120x2880\) 8K\ \(7680x4320\) Custom} {
        radiobutton $r.res.presets.r$row$col -text [string map {\( ( \) )} $preset] \
            -font {-size 9} -variable ::Render2K::resolution_preset \
            -value [string map {\( ( \) )} $preset] \
            -command ::Render2K::update_resolution_fields
        grid $r.res.presets.r$row$col -row $row -column $col -sticky w -padx 4
        incr col
        if {$col > 3} { set col 0; incr row }
    }
    frame $r.res.custom
    pack $r.res.custom -side top -fill x -pady 1
    label $r.res.custom.w -text "Width:" -font {-size 9}
    entry $r.res.custom.width -textvariable ::Render2K::custom_width -width 7 -font {-size 9} -state disabled
    label $r.res.custom.h -text "Height:" -font {-size 9}
    entry $r.res.custom.height -textvariable ::Render2K::custom_height -width 7 -font {-size 9} -state disabled
    label $r.res.custom.px -text "px" -font {-size 9}
    pack $r.res.custom.w -side left -padx {8 2}
    pack $r.res.custom.width -side left -padx 2
    pack $r.res.custom.h -side left -padx {8 2}
    pack $r.res.custom.height -side left -padx 2
    pack $r.res.custom.px -side left -padx 4

    labelframe $r.file -text "Output File" -font {-weight bold -size 9} -padx 6 -pady 4
    pack $r.file -side top -fill x -pady 2
    frame $r.file.f1; pack $r.file.f1 -side top -fill x -pady 1
    label $r.file.f1.l -text "Name:" -width 10 -anchor w -font {-size 9}
    entry $r.file.f1.e -textvariable ::Render2K::filename -font {-size 9}
    pack $r.file.f1.l -side left -padx 4
    pack $r.file.f1.e -side left -padx 4 -fill x -expand 1
    frame $r.file.f2; pack $r.file.f2 -side top -fill x -pady 1
    label $r.file.f2.l -text "Format:" -width 10 -anchor w -font {-size 9}
    pack $r.file.f2.l -side left -padx 4
    foreach fmt {png jpg tiff bmp} {
        radiobutton $r.file.f2.$fmt -text [string toupper $fmt] -font {-size 9} \
            -variable ::Render2K::file_format -value $fmt
        pack $r.file.f2.$fmt -side left -padx 4
    }

    set v $w.main.v
    label $v.info -text "Render a VMD trajectory with the same Blender pipeline used for still images.\nVMD exports each frame; Blender processes them in a single batch; FFmpeg creates the MP4. Changes made during execution apply to the next batch." \
        -anchor w -font {-size 8} -justify left -fg "#555555"
    pack $v.info -side top -anchor w -padx 4 -pady 4

    labelframe $v.frames -text "VMD Frames" -font {-weight bold -size 9} -padx 6 -pady 4
    pack $v.frames -side top -fill x -pady 2
    frame $v.frames.r1; pack $v.frames.r1 -side top -fill x -pady 1
    label $v.frames.r1.ml -text "Molecule:" -font {-size 9} -width 11 -anchor w
    entry $v.frames.r1.m -textvariable ::Render2K::movie_molid -width 8 -font {-size 9}
    label $v.frames.r1.sl -text "Start:" -font {-size 9}
    entry $v.frames.r1.s -textvariable ::Render2K::movie_start -width 7 -font {-size 9}
    label $v.frames.r1.el -text "End:" -font {-size 9}
    entry $v.frames.r1.e -textvariable ::Render2K::movie_end -width 7 -font {-size 9}
    pack $v.frames.r1.ml $v.frames.r1.m -side left -padx {4 2}
    pack $v.frames.r1.sl $v.frames.r1.s -side left -padx {10 2}
    pack $v.frames.r1.el $v.frames.r1.e -side left -padx {10 2}
    frame $v.frames.r2; pack $v.frames.r2 -side top -fill x -pady 1
    label $v.frames.r2.jl -text "Every:" -font {-size 9} -width 11 -anchor w
    entry $v.frames.r2.j -textvariable ::Render2K::movie_stride -width 7 -font {-size 9}
    label $v.frames.r2.jt -text "frame(s)   End=-1 uses the last frame." -font {-size 8} -fg "#555555"
    checkbutton $v.frames.r2.cam -text "Lock VMD camera" -font {-size 9} \
        -variable ::Render2K::movie_lock_camera
    pack $v.frames.r2.jl $v.frames.r2.j $v.frames.r2.jt -side left -padx {4 2}
    pack $v.frames.r2.cam -side right -padx 4

    labelframe $v.out -text "MP4 and Quality" -font {-weight bold -size 9} -padx 6 -pady 4
    pack $v.out -side top -fill x -pady 2
    frame $v.out.r1; pack $v.out.r1 -side top -fill x -pady 1
    label $v.out.r1.l -text "MP4 File:" -font {-size 9} -width 11 -anchor w
    entry $v.out.r1.e -textvariable ::Render2K::movie_filename -font {-size 9}
    pack $v.out.r1.l -side left -padx 4
    pack $v.out.r1.e -side left -padx 2 -fill x -expand 1
    frame $v.out.r2; pack $v.out.r2 -side top -fill x -pady 1
    label $v.out.r2.fl -text "FPS:" -font {-size 9} -width 11 -anchor w
    spinbox $v.out.r2.f -from 1 -to 240 -increment 1 -width 7 \
        -textvariable ::Render2K::movie_fps -font {-size 9}
    label $v.out.r2.cl -text "H.264 CRF:" -font {-size 9}
    spinbox $v.out.r2.c -from 0 -to 51 -increment 1 -width 7 \
        -textvariable ::Render2K::movie_crf -font {-size 9}
    label $v.out.r2.note -text "18 = high quality" -font {-size 8} -fg "#555555"
    pack $v.out.r2.fl $v.out.r2.f -side left -padx {4 2}
    pack $v.out.r2.cl $v.out.r2.c -side left -padx {12 2}
    pack $v.out.r2.note -side left -padx 4

    labelframe $v.assets -text "Resumable Batch" -font {-weight bold -size 9} -padx 6 -pady 4
    pack $v.assets -side top -fill x -pady 2
    checkbutton $v.assets.resume -text "Resume verified assets from the same batch" -font {-size 9} \
        -variable ::Render2K::movie_resume
    checkbutton $v.assets.keep -text "Keep OBJ, MTL, scripts, and PNG files after completion" -font {-size 9} \
        -variable ::Render2K::movie_keep_assets
    checkbutton $v.assets.overwrite -text "Overwrite existing MP4 on completion" -font {-size 9} \
        -variable ::Render2K::movie_overwrite
    pack $v.assets.resume $v.assets.keep $v.assets.overwrite -side top -anchor w -padx 4 -pady 1

    labelframe $v.progress -text "Status" -font {-weight bold -size 9} -padx 6 -pady 4
    pack $v.progress -side top -fill x -pady 2
    scale $v.progress.bar -from 0 -to 100 -resolution 1 -orient horizontal -showvalue 0 \
        -length 420 -variable ::Render2K::movie_progress -state disabled
    label $v.progress.count -textvariable ::Render2K::movie_progress_text -font {-size 8} -anchor w
    label $v.progress.status -textvariable ::Render2K::movie_status -font {-size 8} -anchor w \
        -justify left -wraplength 440
    pack $v.progress.bar -side top -fill x -padx 4
    pack $v.progress.count $v.progress.status -side top -fill x -padx 4 -pady 1
    frame $v.actions; pack $v.actions -side top -pady 6
    button $v.actions.start -text "RENDER MOVIE" -command ::Render2K::do_movie \
        -bg "#1565c0" -fg white -padx 16 -pady 5 -font {-weight bold -size 10}
    button $v.actions.cancel -text "Cancel" -command ::Render2K::cancel_movie \
        -padx 14 -pady 5 -font {-size 9}
    pack $v.actions.start $v.actions.cancel -side left -padx 6

    set m $w.main.m
    label $m.info -text "VMD only selects the profile and provides the geometry color.\nThe following parameters are applied to Blender's Principled BSDF." \
        -anchor w -font {-size 8} -justify left -fg "#555555"
    pack $m.info -side top -anchor w -padx 4 -pady 4

    labelframe $m.profile -text "Blender Profile Associated with the VMD Material" \
        -font {-weight bold -size 9} -padx 6 -pady 4
    pack $m.profile -side top -fill x -pady 2
    frame $m.profile.row
    pack $m.profile.row -side top -fill x
    label $m.profile.row.l -text "Profile:" -font {-size 9} -width 12 -anchor w
    menubutton $m.profile.row.select -textvariable ::Render2K::blender_mat_selected \
        -menu $m.profile.row.select.menu -relief raised -width 20 -anchor w
    menu $m.profile.row.select.menu -tearoff 0
    foreach key [blender_material_keys] {
        $m.profile.row.select.menu add command -label $key \
            -command [list ::Render2K::select_blender_material $key]
    }
    button $m.profile.row.save -text "Save Settings" -font {-size 9} \
        -command ::Render2K::save_blender_material
    pack $m.profile.row.l -side left -padx 4
    pack $m.profile.row.select -side left -padx 4
    pack $m.profile.row.save -side left -padx 8

    labelframe $m.params -text "Principled BSDF Parameters" \
        -font {-weight bold -size 9} -padx 6 -pady 4
    pack $m.params -side top -fill x -pady 4
    set material_fields [list \
        [list roughness "Roughness" 0.0 1.0 0.01] \
        [list metallic "Metallic" 0.0 1.0 0.01] \
        [list specular "Specular Level" 0.0 1.0 0.01] \
        [list alpha "Alpha" 0.0 1.0 0.01] \
        [list transmission "Transmission (glass)" 0.0 1.0 0.01] \
        [list ior "IOR" 1.0 3.0 0.01]]
    set row 0
    foreach field $material_fields {
        foreach {name label low high step} $field { break }
        label $m.params.l$row -text "$label:" -font {-size 9} -width 18 -anchor w
        spinbox $m.params.s$row -from $low -to $high -increment $step -width 8 \
            -textvariable ::Render2K::blender_mat_$name -font {-size 9}
        label $m.params.r$row -text "$low - $high" -font {-size 8} -anchor w
        grid $m.params.l$row -row $row -column 0 -sticky w -padx 4 -pady 1
        grid $m.params.s$row -row $row -column 1 -sticky w -padx 4 -pady 1
        grid $m.params.r$row -row $row -column 2 -sticky w -padx 4 -pady 1
        incr row
    }

    label $m.note -text "Alpha produces clear transparency; Transmission produces physical glass and requires Alpha=1.\nSpecular Level uses Specular in Blender 3.x and Specular IOR Level in Blender 4.x." \
        -anchor w -font {-size 8} -justify left -fg "#555555" -wraplength 440
    pack $m.note -side top -anchor w -padx 6 -pady {0 2}
    label $m.status -textvariable ::Render2K::blender_mat_status \
        -anchor w -font {-size 8} -justify left -fg "#006600" -wraplength 440
    pack $m.status -side top -fill x -padx 6 -pady {0 4}
    load_blender_material

    frame $w.act
    pack $w.act -side top -pady 4
    button $w.act.render -text "RENDER IMAGE" -command {::Render2K::do_render} \
        -bg "#4CAF50" -fg white -padx 24 -pady 6 -font {-weight bold -size 11}
    button $w.act.close -text "Close" -command ::Render2K::close_window \
        -padx 16 -pady 6 -font {-size 9}
    pack $w.act.render -side left -padx 6
    pack $w.act.close -side left -padx 6

    update_background_controls
    update_resolution_fields
    movie_update_controls
    show_tab r
}
